#!/usr/bin/env python3
"""
zTheme Build Script - Concatenate all CSS source files
"""
import os
from pathlib import Path

# Define the import order (from zTheme.css)
CSS_IMPORTS = [
    # Core Variables & Base Styles
    'css_vars.css',
    'zReboot.css',
    'zMain.css',
    'zTypography.css',
    
    # Layout & Structure
    'zContainers.css',
    'zGrid.css',
    'zColumns.css',
    'zGutters.css',
    'zSpacing.css',
    'zFloat.css',
    
    # Components
    'zAccordion.css',
    'zAlerts.css',
    'zBadges.css',
    'zBreadcrumb.css',
    'zButtons.css',
    'zButtonGroup.css',
    'zCards.css',
    'zCarousel.css',
    'zCollapse.css',
    'zDropdown.css',
    'zFigures.css',
    'zForms.css',
    'zListGroup.css',
    'zModal.css',
    'zOffcanvas.css',
    'zNav.css',
    'zNavbar.css',
    # 'zPanels.css',  # Not in directory list
    'zTables.css',
    'zFooter.css',
    'zSections.css',
    'zHero.css',
    
    # Widgets
    'zProgress.css',
    'zSpinner.css',
    'zPagination.css',
    'zPopover.css',
    'zScrollspy.css',
    'zToast.css',
    'zTooltip.css',
    'zLinks.css',
    'zRatio.css',
    'zVisually.css',
    
    # Effects & Utilities
    'zBackground.css',
    'zBorders.css',
    'zBreakpoints.css',
    'zColors.css',
    'zDisplay.css',
    'zFlex.css',
    'zIcons.css',
    'zInteractions.css',
    'zOverflow.css',
    'zPosition.css',
    'zShadows.css',
    'zSizing.css',
    'zText.css',
    'zVerticalAlign.css',
    'zEffects.css',
    'zMedia.css',
    'zImages.css',
    
    # E-commerce (Optional)
    'zShop.css',
    'zAddToCart.css',
    'zSearch.css',
    
    # Authentication
    'zLogin.css',
    
    # Development Tools
    'zDev.css',
]

def build_ztheme():
    """Concatenate all CSS files into dist/ztheme.css"""
    base_dir = Path(__file__).parent
    src_dir = base_dir / 'src' / 'css'
    dist_dir = base_dir / 'dist'
    output_file = dist_dir / 'ztheme.css'
    
    # Ensure dist directory exists
    dist_dir.mkdir(exist_ok=True)
    
    print(f"🔨 Building zTheme CSS...")
    print(f"   Source: {src_dir}")
    print(f"   Output: {output_file}")
    print()
    
    with open(output_file, 'w', encoding='utf-8') as outfile:
        # Write header
        outfile.write('/**\n')
        outfile.write(' * ═══════════════════════════════════════════════════════════════\n')
        outfile.write(' * zTheme - Complete CSS Framework (Compiled)\n')
        outfile.write(' * ═══════════════════════════════════════════════════════════════\n')
        outfile.write(' * This file is automatically generated from src/css/*.css\n')
        outfile.write(' * DO NOT EDIT THIS FILE DIRECTLY - Edit source files instead\n')
        outfile.write(' */\n\n')
        
        # Concatenate each CSS file
        for css_file in CSS_IMPORTS:
            source_path = src_dir / css_file
            
            if not source_path.exists():
                print(f"⚠️  Skipping {css_file} (not found)")
                continue
            
            print(f"✅ Including {css_file}")
            
            # Write file marker comment
            outfile.write(f'\n/* ========== {css_file} ========== */\n')
            
            # Read and write file contents
            with open(source_path, 'r', encoding='utf-8') as infile:
                outfile.write(infile.read())
            
            outfile.write('\n')
    
    # Get file size
    size_kb = output_file.stat().st_size / 1024
    
    print()
    print(f"✨ Build complete!")
    print(f"   Output: {output_file}")
    print(f"   Size: {size_kb:.1f} KB")

if __name__ == '__main__':
    build_ztheme()
